name: Java CI

on:
  push:
    branches:
        - java

jobs:
  # Job for building the application
  build:
    runs-on: ubuntu-latest # Specifies the runner
    steps: # Steps to execute in the build job
      - uses: actions/checkout@v3 # Checks out the repository code
      - name: Set up JDK 11
        uses: actions/setup-java@v3 # Sets up Java Development Kit version 11
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn compile # Compiles the code using Maven

  # Job for testing the application
  test:
    needs: build # This job depends on the successful completion of the build job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test # Runs tests using Maven

  # Job for deploying the application
  deploy:
    needs: test # This job depends on the successful completion of the test job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Deploy
        run: echo "Deploying application..." # Placeholder for deployment commands
        # Add your actual deployment commands here
