name: Node.js CI

on:
  push:
    branches:
      - nodejs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Node.js
        uses: actions/setup-node@v3 # This ensures that the specified Node.js version is installed and available for subsequent steps

        with:
          node-version: '14.0' # You could replace it with a different version of Node.js

      - name: Install dependencies
        run: npm install

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change to project directory
        run: cd NodeGuide

      - name: Show files
        run: ls -la
        
      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: echo "Deploying application..."